### ISSUE TITLE
Ice not being frozen in loaded chunks

### ISSUE THREAD

**Issue by Pixel1011** [Geitenijs/KeepChunks#10]
**Is your feature request related to a problem? Please describe.**
I guess, ice in my ice farm wasnt being frozen while the chunks were loaded

**Describe the solution you'd like**
I would like ice to be frozen when it is in the loaded chunk as it seems to not be freezing in loaded chunks at the moment

**Additional context**

**Comment by Geitenijs** [comment]
This is probably due to Bukkit/Spigot limitations.
