### ISSUE TITLE
Incompatible with new WE and WG

### ISSUE THREAD

**Issue by RaidForums** [Geitenijs/KeepChunks#11]
So I don't know if this is because of Spigot I read somewhere that it might be but for one the loaded chunks they don't keep crops growing? Could I do this maybe without spigot but just another installation?

Anyway other than that there is the current problem that 1.14.4 has an updated worldedit and worldguard and keepchunks plugin isn't compatible with them when you try a plugin command to do with worldedit or worldguard it won't work with the new versions of WE and WG.

**Comment by Geitenijs** [comment]
It's indeed because of Bukkit/Spigot, and unfortunately there's nothing we can do about it.

Can you please post the error message from your console when using WE/WG?

**Comment by RaidForums** [comment]
It says you require WorldEdit / WorldGuard 7.0.0 when I have 7.0.1, you should just enable me to use any worldguard version newer than 7 not limit me to 7.0; There's no error in the console.

**Comment by Geitenijs** [comment]
Will fix soon. Thanks for reporting.

**Comment by Geitenijs** [comment]
Will be fixed in 1.5.13
