### ISSUE TITLE
KeepChunks crashing server

### ISSUE THREAD

**Issue by Vehzx** [Geitenijs/KeepChunks#13]
**Describe the bug**
When trying to save chunks, it gets a good 150 blocks by 150 blocks in, then the server crashes while the console is spammed with the error.

**To Reproduce**
1. keepregion (set some co ords, i tried 50 50 -50 -50 and it crashed still)
2. Use feature '....'
3. See error: https://pastebin.com/qYsP3uWi

**Expected behavior**
The chunks to be saved without crashing?

**Screenshots**
See pastebin for the error, not really a need for a screenshot

 - OS: Win 10
 - Server Software: Paper Build #167
 - Server Version: 1.14.4
 - WorldEdit Version (if applicable) The latest (although I didnt use this with the plugin so it shouldn't matter)
 - WorldGuard Version (if applicable) The latest (although I didnt use this with the plugin so it shouldn't matter)
 - Full list of plugins: https://i.gyazo.com/89d0e9c961aaa63cc13bfc836bf8ad60.png

**Comment by Geitenijs** [comment]
Have those chunks ever been loaded before? Like, have they been generated?
It looks like your server had a hard time loading all the chunks at once.

**Comment by Geitenijs** [comment]
@Vehzx Is this still a problem for you?
