### ISSUE TITLE
[Feature Request] Please add support for Sponge server

### ISSUE THREAD

**Issue by s-kk** [Geitenijs/KeepChunks#14]
**Describe the solution you'd like**
Please add support for Sponge server.

**Additional context**
It's a really good plugin for chunk loading, but can't get it to work on Sponge server. I would very appreciate it if it's possible for it to be on Sponge.

Thanks in advance!

**Comment by Geitenijs** [comment]
I'm sorry, but I won't be adding support for Sponge anytime soon.
