### ISSUE TITLE
Mob Spawner Loading

### ISSUE THREAD

**Issue by netram2** [Geitenijs/KeepChunks#15]
**Is your feature request related to a problem? Please describe.**
my friends and I would like to build farms offline, which at the same time keep monster spawner active

**Describe the solution you'd like**
My suggestion would be if in the config a punk called "spawner-loading" is added, which ensures that the spawner remain active

**Additional context**
Would be very happy if they can implement this

**Comment by nate-moo** [comment]
I would also like this, as this was the main purpose for me to add this to my server

**Comment by Geitenijs** [comment]
I would love to be able to add this to KeepChunks, however it is sadly not possible due to Minecraft limitations.
