### ISSUE TITLE
Ignoring NoSuchMethodException, does this break the plugin?

### ISSUE THREAD

**Issue by jackstrosahl** [Geitenijs/KeepChunks#16]
Sorry but I'm not reporting a bug necessarily, I also cancel `ChunkUnloadEvent` in my plugin and that [seems](https://hub.spigotmc.org/javadocs/bukkit/index.html?org/bukkit/event/block/BlockExplodeEvent.html) to be gone in 1.14.
So I saw this:
https://github.com/Geitenijs/KeepChunks/blob/6de4934a05f664c3bf9eb1b3a57c0a67f547b456/src/com/geitenijs/keepchunks/Events.java#L26-L29
Will this just do nothing on 1.14?  If so, does that break this plugin?

**Comment by Geitenijs** [comment]
It doesn't break the plugin. We use the new forceload API in 1.14

**Comment by jackstrosahl** [comment]
Ah ok, I noticed that I was also using that in my plugin, so cancelling this event was pointless.  🤦

**Comment by Geitenijs** [comment]
Haha no worries, took some time for me to figure it out as well ;)
