### ISSUE TITLE
1.5.14 Not Working (MC 1.14.4)

### ISSUE THREAD

**Issue by Fordy436** [Geitenijs/KeepChunks#19]
Running MC version 1.14.4 with WG 7.0.1 and WE 7.0.1. After restarting the Server, saved chunks stay loaded for a while, but then stop being loaded. Previous versions of the Plugin worked fine, but now the Plugin only keeps chunks loaded until you restart the Server.

No error messages upon Server start.

**Comment by Fordy436** [comment]
Reverted back to V1.5.12 which works fine.

**Comment by Geitenijs** [comment]
Thanks for letting me know. Will fix it asap

**Comment by Geitenijs** [comment]
Fixed in v1.6.0
