### ISSUE TITLE
Feature request: Formatting codes and localization

### ISSUE THREAD

**Issue by SlimeDog** [Geitenijs/KeepChunks#20]
**Is your feature request related to a problem? Please describe.**
The default console error/warn messages, for example, are red, which are unreadable on my blue console.

**Describe the solution you'd like**
Plan A: configuration option to remove all formatting codes
Plan B: language file, so all messages can be localized, both in-game at on console
Plan C: both

**Additional context**

**Comment by Geitenijs** [comment]
Console messages are currently not any different from the in-game ones. Will remove colours from the console soon. Thanks!

**Comment by Geitenijs** [comment]
KeepChunks v1.6.1 contains an option to strip colours from the console.

Happy 2020!
