### ISSUE TITLE
"An Internal error occurred while attempting to perform this command"

### ISSUE THREAD

**Issue by Ziv2004** [Geitenijs/KeepChunks#24]
Hey, I'm Ziv
me and my friends are playing on a minehut server on the latest version on minecraft (15.2)
I added keepchunks and when I try to run /keepchunks minecraft says: "An Internal error occurred while attempting to perform this command"
also when I type /plugins reload , all of the other plugins show in green while keepchunks shows in red.
Is keepchunks not compatible with 15.2 or is it something else? I have no idea but I whold very much like to know!

**Comment by Geitenijs** [comment]
Hi!

What server software are you running? Use /ver and get me the exact output. I'd also like to have a full server log, so I can see what the problem is.
