### ISSUE TITLE
Problem with worldedit dependency

### ISSUE THREAD

**Issue by wanou067** [Geitenijs/KeepChunks#26]
Hello,

I'm using your plugin for my server running on 1.12.2. As you said, i downloaded a version wich is compatible with spigot 1.12.2 (KeepChunks v1.5.13). The problem is that to use worldedit functionnality, i have to have worldedit v7.0.0 or higher but the version 7.0.0 of worledit is not compatible with spigot 1.12.2 so i'm using worldedit 6.1.9. How can i use your plugin with spigot 1.12.2 and worldedit ?

**Comment by Geitenijs** [comment]
Hi!

You can use an [older version](https://transfer.sh/AosQy/1.4.4.jar) with WE 6 support. Keep in mind that there have been quite some improvements in later versions. It should still work fine on 1.12.2 though!
