### ISSUE TITLE
<feature> Please add keepregion for 1.12.2 using WorldGuard 6.2.2

### ISSUE THREAD

**Issue by madtomic** [Geitenijs/KeepChunks#3]
I am using 1.12.2 and I can't use Worldguard 7.x. Please consider to add support for keepregion for 
WorldGuard 6.2.2 Thanks

**Comment by Geitenijs** [comment]
I'm sorry, but the development is focused on 1.13+. I don't have much time either.
You can use /kc chunkinfo at 2 opposite corners in your WG region to get the chunk coordinates, which you can then use in /kc keepregion coords.
If this doesn't fulfill your needs, consider upgrading to 1.13.2.

**Comment by madtomic** [comment]
/kc keepregion coords -18 -550 -325 -221 world

I tried this and nothing happen.
