### ISSUE TITLE
Add support for FAWE

### ISSUE THREAD

**Issue by prldm** [Geitenijs/KeepChunks#33]
Could you please add support for FAWE (FastAsyncWorldEdit)?
"FAWE is a fork of WorldEdit that has huge speed and memory improvements and considerably more features."

**Comment by dorrzun** [comment]
Should be doable, but I'll look into this and follow up if it's cool with Geitenijs, I know there is some discussion of switching to async loading for obvious performance reasons. Looking to bring that feature in alongside the new permission system (hopefully by the end of this year?) :)

**Comment by berlincount** [comment]
I'd like to second this request :)

**Comment by ErythroCraft** [comment]
Please give support for [AsyncWorldEdit](https://github.com/SBPrime/AsyncWorldEdit) first.

**Comment by Geitenijs** [comment]
Better late than never... Added in 1.7.0
