### ISSUE TITLE
no mob spawn if player == 0

### ISSUE THREAD

**Issue by sctnightcore** [Geitenijs/KeepChunks#34]
![image](https://user-images.githubusercontent.com/23263315/102109489-ae7dd300-3e66-11eb-90b0-3d1ee7c69fe3.png)

if i use /kc reload
![image](https://user-images.githubusercontent.com/23263315/102109764-fd2b6d00-3e66-11eb-85bc-8093d2a548ac.png)

If I wait without / kc reload.
Nothing happened

Minecraft 1.16.4
Plugins (5): UltimateTimber, KeepChunks, SinglePlayerSleep, SignWarper, BlockLocker
Test: mob farm -> no mob spawn

if player near
![image](https://user-images.githubusercontent.com/23263315/102116867-2dc3d480-3e70-11eb-9e14-167f619cde00.png)
else
![image](https://user-images.githubusercontent.com/23263315/102117136-88f5c700-3e70-11eb-8598-c0b70ae83895.png)

**Comment by dorrzun** [comment]
Hi!

Last I checked, monsters will not spawn unless a player is nearby. That isn't something that can be affected by the plugin, and is a part of the vanilla game mechanics :)
