### ISSUE TITLE
Keepregion command does not work

### ISSUE THREAD

**Issue by philmeth** [Geitenijs/KeepChunks#35]
Hey :)

So I'm trying to keep a set region. So far I have tried it with setting the coordinates manually 
(/kc keepregion coords 0 -1 25 22 [worldname])
and with a preset region from worldguard
(/kc keepregion worldguard [regionname] [worldname]).
I always get the same message reminding me of the command usage.

Stupid question: What am I doing wrong? :D 

Greetings!

**Comment by Geitenijs** [comment]
Totally missed this issue. If it's still a problem feel free to reopen
