### ISSUE TITLE
region ids, toggle, active/inactive time interval

### ISSUE THREAD

**Issue by oggimaster** [Geitenijs/KeepChunks#36]
It would be great to have an **on/off toggle** for regions and even a **selectable time interval** when the region should be loaded. Therefore **region ids** also have to be implemented to differenciate from another.

**Region ID**: You mark a single chunk or a specific region/area. The plugin assigns automatically a natural number starting at 1 to "max of datatype". Also naming would be nice. Therefore an alias could work - ID: 1 ; NAME: Slimefarm -> /kc list -> (id: 1, name: Slimefarm, chunk: [chunks])

**on/off toggle**: After assigning a region with id and name, you can toggle if this region is activly loaded or not. Like keepchunks would be on hold or working. I dont mean a function where you are able to force unload this region.

**time interval**: An extension to the on/off toggle - a selectable time interval when the region should be loaded. This would be nice for a server with limited ressources. At day and evening the server is full with players and when the most people log out at around 10pm o'clock, automatic farms could be loaded. Or just when no one is online between 3am an 7am. I would suggest to connect the time to the servers time, so its independent from minecrafts tick based time.

**Comment by Geitenijs** [comment]
For the region ids, use WorldGuard. And for a time interval you could use command blocks or a plugin like [this](https://www.spigotmc.org/resources/commandscheduler.94797/)
