### ISSUE TITLE
Crops don't grow

### ISSUE THREAD

**Issue by Grisbal** [Geitenijs/KeepChunks#4]
Hello there!
On my paper server, plants are not growing. Command blocks and so on work properly. Is this issue known?

**Comment by Geitenijs** [comment]
Hi!
Sadly, this won't be possible until Spigot/Paper adds support for making chunks tick when there are no players around.

**Comment by Grisbal** [comment]
Thank you for your quick answer. Thats truly sad. I hope there is coming an update soon. Does it work on Bukkit?

**Comment by FocuzJS** [comment]
could you create a spectator "bot" entity in the location you want crops to grow? sorry im not familiar with the spigot API

**Comment by RaidForums** [comment]
Yeah I have the same questions as the 2 above, does it work with Bukkit? @Geitenijs
