### ISSUE TITLE
Add support for 1.18

### ISSUE THREAD

**Issue by preludium975** [Geitenijs/KeepChunks#45]
`[Server thread/INFO]: [KeepChunks] Your server version is not compatible with this release of KeepChunks. Supported versions are: 1.17, 1.16, 1.15, 1.14 and 1.13.2. You can download other releases at: https://www.spigotmc.org/resources/23307`

**Comment by Underlyingglitch** [comment]
I haven't really inspected any of the source code yet, but you should be able to change just the version check to get it working. Last time only the version check was updated to add support for 1.17.

I'll check on that later today

**Comment by kqfflo** [comment]
It assue it should work with 1.18 but I am not that into java to be able to compile this. The needed code changes are minimal.

**Comment by jonteohr** [comment]
Should be fixed with #46

**Comment by Geitenijs** [comment]
Done, thanks!
