### ISSUE TITLE
Mob Farm (not working)

### ISSUE THREAD

**Issue by SimonOO7** [Geitenijs/KeepChunks#47]
Hey there,

the chunk loader is not working for Iron Golem Farms, Creeper Farms etc. Do I do something wrong or does this plugin doesnt support mob Farms?
Thanks for your answer!

Yours
Simon

**Comment by emielderckx** [comment]
Golem farms should work.

But mob farms that rely on spawning do not work, that is just the way Minecraft works. https://minecraft.fandom.com/wiki/Spawn

**Comment by SimonOO7** [comment]
so only golem farms work but no gold(pigmen) farms etc
or are there some more farms that work?

**Comment by emielderckx** [comment]
All farms that don't require a player to have a spawn radius

**Comment by SimonOO7** [comment]
Sorry but im not really good at knowing minecraft stuff :) Can u please state some examples?

**Comment by surfrock66** [comment]
Most mob spawning requires players to be nearby.  Spawners require a player to be within a 16 block radius of the spawner to make mobs, and for general mobs (like hostile mobs in a general mob farm) you have to be more than 24 and less than 128 blocks away.  Even if a chunk is loaded, if a player isn't there, mobs don't spawn.

You need something like this, though it's abandoned: https://github.com/KP56/Fake-Players-Spigot-Plugin
