### ISSUE TITLE
Blocks that keep chunks loaded.

### ISSUE THREAD

**Issue by MXKhronos** [Geitenijs/KeepChunks#49]
Hello, I have a simple feature request.

I run a small private server with 3-5 players and it would be great when we log out, our furnaces and redstone clocks could keep running. I use the latest version of papermc 1.18 so the optimizations generally likes to unload as much chunks as possible.

I would like to request for a feature where I could add different block ids (only blocks that are not pushable by pistons) into a list. When those blocks are placed or destroyed, the chunk id is added/removed from the datafile that marks chunks to be force loaded. Blocks such as player-placed Furnaces, Chests, Redstone, etc..

I hope this is not too much work, regardless of this request being accepted, great work on the plugin again!
~Khronos

**Comment by dorrzun** [comment]
Hi @MXKhronos ! I don't think we'd consider adding a feature that works with such common items like that. I can see the use case, but it's quite niche and just not a priority at the moment. 

I'm currently dusting off the codebase for the first time in awhile, and unfortunately my priorities are with a new permission system, in-game chunk management window, and general housekeeping.

When I get these other things completed, I'd be more than willing to write you a custom JAR to use :)

**Comment by Geitenijs** [comment]
This would be quite inefficient bc it'd require us to log every furnace/redstone that gets placed/destroyed. And if a block gets removed using a plugin like Worldedit, we wouldn't know.

I'm not really a fan of adding this feature, sorry.

**Comment by MXKhronos** [comment]
@Geitenijs Understandable, haven't thought about the technical details with other dependencies.
@dorrzun Thanks for the offer, but no worries~ I'll take a shot at it on my own. :)

Keep up the good work and have a great day!
Khronos~
