### ISSUE TITLE
<feature> please add keepregion for 1.11.2 using worldguard 6.2

### ISSUE THREAD

**Issue by Mikimoka** [Geitenijs/KeepChunks#5]
**Is your feature request related to a problem? Please describe.**
I'm frustrated since there are no older version. Or combatible mode. This plugin would be perfect solutions to my server heeh

**Describe the solution you'd like**
Solution release older version that works in 1.11.2 

**Additional context**

**Comment by Geitenijs** [comment]
Sorry for the inconvenience, [here](https://transfer.sh/FcbzT/1.4.4.jar)'s an older version of KeepChunks compatible with WE 6.
