### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by SgtMate** [Geitenijs/KeepChunks#51]
**Describe the bug**
The documentation on spigotmc.org does not clarify that the coordinats entered with the "coords" option are meant to be chunk coordinates. This leads to servercrashes if the user enters blockcoords.  Please add this to the documentation and add a warning for the users so that this is prohibited when using the corresponding commands. 

**To Reproduce**
select a region of a few dozent blocks and enter the blockcoords in the following command
just use "/keepchunks keepregion coords SOME_BLOCK_COORDS WORLDNAME"

**Expected behavior**
Warning when adding huge regions, before applying the changes. Information that chunkcoords are required. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux
 - Server Software Spigot
 - Server Version 1.18.2

**Additional context**
This is only a documentation issue.

**Comment by dorrzun** [comment]
Hi! Looks like our previous documentation that mentioned chunk coordinates got lost somewhere...

We have a permission system back in the works, with some admin configured chunk load limits, so hopefully those should address the issues along with the documentation.

Thanks!

**Comment by SgtMate** [comment]
Yes, this might help. 

But it would also be a helpfull feature if the plugin asked for a second approval if you try to load X amount of chunks with one command. Just so you can overthink your decision if it has the potential to crash the server. 
Would be nice if you could configure X in the config.

And please add the mentioned edit to the documentation, this will prevent many first setup issues.

Thanks for your fast answer! And thanks for the great plugin!

**Comment by Geitenijs** [comment]
@dorrzun This definitely used to be present on the Spigot page... I must've removed it by accident.

@SgtMate I've just added it back to the Spigot page! Thanks for pointing this out.

**Comment by Geitenijs** [comment]
@SgtMate Please do! I probably won't have the time to add it anytime soon, but @dorrzun may have. It's a good thing to add anyway

**Comment by SgtMate** [comment]
@Geitenijs Ok, Ill write the request this evening. 😄

**Comment by SgtMate** [comment]
#53 Its added 😄 
Thanks for the huge support! 😊
