### ISSUE TITLE
KeepChunks 1.6.10 notifies of a newer version

### ISSUE THREAD

**Issue by kqfflo** [Geitenijs/KeepChunks#52]
**Describe the bug**
KeepChunks seems to consider 1.6.10 as a lower version to 1.6.9

**To Reproduce**
1. Install latest release 1.6.10
2. See startup log
3. Log shows notification for "updating" to 1.6.9

**Expected behavior**
No notification 

**Screenshots**
`[17:45:24 INFO]: [KeepChunks] A new release of KeepChunks, v1.6.9, is available! You are still on v1.6.10.`

**Environment (please complete the following information):**
 - Ubuntu 20 LTS
 - PaperMC
 - 1.18.2
 - WorldEdit n/a
 - WorldGuard n/a
 - Plugins (25): AuctionMaster, CMILib, ChestSort, Citizens, CoreProtect, Essentials, EssentialsChat, EssentialsDiscord, EssentialsGeoIP, GSit, Jobs, KeepChunks, LockettePro, LuckPerms, MrCore_BukkitImpl, PlaceholderAPI, ProtocolLib, Quests, QuestsGUI, ServerUtils, SmoothTimber, ToolStats, Vault, dtlTraders and dynmap

**Additional context**
Maybe the code only checks on digit. So 10 becomes 1 which is lower 9 and therefore the notification gets triggered.

**Comment by SgtMate** [comment]
I just updated and at least I didnt got the prompt. Maybe the spigot api was a bit laggy? 
Maybe try again if it works now 😄

**Comment by Geitenijs** [comment]
The Spigot API returns an old value, the code removes the dots and compares so that shouldn't be an issue.

Please let me know when the issue persists

**Comment by Geitenijs** [comment]
@kqfflo Issue is no longer present for me, tested it on multiple servers.
