### ISSUE TITLE
Option to auto-save and auto-search intervall.

### ISSUE THREAD

**Issue by ErythroCraft** [Geitenijs/KeepChunks#54]
Hi

I would like an option to auto-save and auto-search.
[How often chunks look for rails and entities, if enabled.]
The options should search for placed enabled rails and entities.
Than save it automatically.

**Additional context**
Example:

autoSaveInterval: true/false
permissionGroups:
 - op
 - member
 - default
isPermissionGroupBlacklist: true/false

worlds:
 - world_1
 - world_2
isWorldListBlacklist: true/false

entitySearchEnable: true/false
entities:
 - entity_1
 - entity_2
isEntityListBlacklist: true/false

railSearchEnable: true/false
searchAllRails: true/false #If true, KeepChunks search all rails in world. If false, KeepChunks search only placed rails by player.

**Comment by dorrzun** [comment]
Although this is a cool idea, the Entities aspect is a little outside of the plugin's scope. KeepChunks is primarily a back-end tool focused on simplifying the _manual_ chunk loading/unloading process for desired areas. (In addition to a WIP permission system)

In the current implementation, Keep/ReleaseRail performs a one time nearest neighbor search until all connected rails from the given point have been discovered & loaded. There is no continuous world checking or monitoring at this time.

Scalability is very important when developing features that perform rapid, synchronous world manipulation/querying (Issue #53 elaborates on this problem), so your feature could realistically add a considerable load to servers with hundreds of players, in addition to whatever commands they send through (assuming they are admin, or the aforementioned permission system is enabled). 

I'll add this to the backlog and see what @Geitenijs says, but implementing this idea would require the plugin to monitor every block break/place event, which is quite expensive, so would have to be disabled by default.
