### ISSUE TITLE
Cactus (and maybe other crops) do not grow

### ISSUE THREAD

**Issue by IgnorantMountaineer** [Geitenijs/KeepChunks#57]
**Describe the bug**
When a cactus is placed in a chunk, then the command /kc keepchunk current is executed in the same chunk, the cactus will not continue to grow once a player has left the chunk

**To Reproduce**
See above, place Cactus in chunk, keep the chunk, leave the chunk

**Expected behavior**
The cactus to continue to grow after a player has unload the chunk

**Screenshots**
Not needed

**Environment (please complete the following information):**
 - OS: Windows and Linux
 - Paper
 - 1.19
 - WorldEdit Version (if applicable) N/A
 - WorldGuard Version (if applicable) N/A
 - Full list of plugins: None

**Additional context**
This is an issue with our cactus farm not working. it works by cactus growing, then automatically breaking, then flowing down water pathways into hoppers and then into chests

**Comment by Geitenijs** [comment]
Crops require the chunk to 'tick' which only happens when a player is nearby. Unfortunately this is impossible to simulate using regular APIs

**Comment by IgnorantMountaineer** [comment]
Got it, thank you I wasn't aware of that.
