### ISSUE TITLE
Unload loaded chunks when server is busy

### ISSUE THREAD

**Issue by RealStoneSword** [Geitenijs/KeepChunks#59]
Maybe when the TPS becomes to low or to many players are online the chunks will be unloaded. This could be an option in the config file or a command.

**Comment by dorrzun** [comment]
Hi!

I certainly like the idea, but it might conflict with the logic behind #53 .
The argument being that server owners should be mindful/place an upper limit on the number of chunks their server can load.
This amount will vary heavily between hardware and game world activity, so there's no effective way to create a universal solution.

These kinds of granular performance changes are awesome, but I can't get to them just yet.
I still appreciate you taking the time to give feedback here!
