### ISSUE TITLE
Consider fitting the following Folia?

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [Geitenijs/KeepChunks#62]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
I hope your plugin will work with Folia, I love your plugin, but I'm sorry it doesn't work with Folia

**Additional context**
None

**Comment by dorrzun** [comment]
Hi @xiaoyueyoqwq. I've done some previous investigation into support for Paper, and while it may be possible, it's not a priority at this time. I will keep this issue open for now and update you with more recent findings down the line.

**Comment by xiaoyueyoqwq** [comment]
> Hi @xiaoyueyoqwq. I've done some previous investigation into support for Paper, and while it may be possible, it's not a priority at this time. I will keep this issue open for now and update you with more recent findings down the line.

Okay, thanks for your support :D
