### ISSUE TITLE
Buy chunks 

### ISSUE THREAD

**Issue by SkyGamer911** [Geitenijs/KeepChunks#7]
**Is your feature request related to a problem? Please describe.**
no it is not a problem related to my request 
**Describe the solution you'd like**
The abillity to use it together with lets say plotsquared or plotme (or similar) 
and to sell "always chunkloaded" plots for donators 
or make the plot chunkload when players are online
all these abilities should be possible regardless of area or similar

i hope this is possible 
**Additional context**
N/A

**Comment by Geitenijs** [comment]
I'm sorry, but I won't add this functionality, as it's too complex for a simple plugin like KeepChunks. 
You could, however, create a plugin which hooks into P2 and executes KeepChunks commands.
