### ISSUE TITLE
KeepChunks is holding unlisted chunks.

### ISSUE THREAD

**Issue by NobleStrike** [Geitenijs/KeepChunks#8]
**Describe the bug**
Keepchunks is keeping chunks loaded that it shouldn't and unable to unload all those chunks when the chunks are released. See below.

**To Reproduce**
1. Create empty world with 0 chunks loaded. (Confirmed no chunks are loaded with essentialsx /gc)
2. Go into a fresh world and run "/kc keepchunk current" to a single chunk, leave world and wait 5 minutes.
3. Check how many chunks are loaded with essentialsx /gc, it shows 25 chunks are loaded. Not just 1.
4. Run "/kc releasechunk current" on that chunk and leave that world for over 5 minutes
5. 9 chunks are now permanently loaded forever in that world in a glitched state. Checked with essentialsx /gc

**Expected behavior**
In the past the plugin only loads the chunks I select and removes those chunks when I release them. I was able to keep about only 50 or so chunks loaded, now for some reason it jumped to 636 when no one is in the world, my above test confirmed its related to keepchunks.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
- Java version: 1.8.0_191
 - Server Software: Spigot
 - Server Version: git-Spigot-935adb3-a0e4747 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
 - KeepChunks version: v1.5.12
- Plugin list and all versions: https://pastebin.com/0JTr6iQ0

**Additional context**
Keep chunks Data file does not show the glitched chunks, only the ones I selected to be loaded.
I tried to load up a clone of a glitched world under a new name that keepchunks isn't tracking to see if it would release the chunks glitched, they do not, meaning the map is now i fear mildly corrupt somehow.
While I am running multiverse-core i have all my worlds set to NOT "keepspawninmemory" which in the past means when no one is in a world, it has zero chunks loaded UNLESS keepchunks has certain chunks loaded.

Config details:
general:
  debug: false
  releaseallprotection: true
updates:
  check: true
  notify: true
chunkload:
  all: false
  dynamic: true
  onstartup: true
  onworldload: true

Data.yml:
chunks:
- 15#-49#Spawn
- -4#8#Spawn
- 16#-48#Spawn
- 3#6#Spawn
- 12#-12#Spawn
- 14#-50#Spawn
- 13#-48#Spawn
- 11#23#Spawn
- -3#-23#Spawn
- -6#18#Spawn
- -2#-24#Spawn
- 14#23#Spawn
- 0#-7#Spawn
- -3#3#Spawn
- -1#-25#Spawn
- 1#-7#Spawn
- -2#-23#Spawn
- 1#10#Spawn
- -1#2#Spawn
- 15#-10#Spawn
- -13#1#Spawn
- 4#-16#Spawn
- 14#-49#Spawn
- 12#-13#Spawn
- 2#11#Spawn
- 15#23#Spawn
- 13#-12#Spawn
- -8#17#Spawn
- 13#23#Spawn
- 11#-11#Spawn
- -19#-18#Spawn
- -3#-15#Spawn
- -7#12#Spawn
- -8#11#Spawn
- -1#5#Spawn
- 16#-50#Spawn
- 0#12#Spawn
- 1#11#Spawn
- 2#10#Spawn
- 13#-13#Spawn
- -8#12#Spawn
- -1#-7#Spawn
- 12#23#Spawn
- -7#7#Spawn
- 4#10#Spawn
- -3#-24#Spawn
- -1#11#Spawn
- 1#18#Spawn
- -7#11#Spawn
- 15#-47#Spawn
- 0#5#Spawn
- 17#-50#Spawn

Please let me know if you need any more info to help find a solution to this issue. My 6 year old City spawn map is affected the most by this bug, Thank you for your time and help.

**Comment by NobleStrike** [comment]
Once this is patched I will try to run my maps through region fixer and try clearlags chunk unloader command to see if it repairs my map before loading it back up with keepchunks.

**Comment by NobleStrike** [comment]
Upon further use I dont even think its keeping chunks that its listed to keep loaded even loaded anymore. I can't code nor do I fully understand why the plugin is acting like this. Thank you for your help.

**Comment by Geitenijs** [comment]
Spigot 1.14 has completely ruined the chunk loading API. This makes it very difficult to keep our configuration synced with the server. Previously, we could just tell the server on-demand not to unload specific chunks.

If chunks are not loaded, but they do appear in the /forceload command, then that's a Spigot problem.

**Comment by NobleStrike** [comment]
Can you work with papermc to have them fix this? They are typically more willing to stray away from typical code to fix bugs like this. I'm sure you already tried to work with spigot to fix this. Hopefully a temporary loophole can be found.

Thank you for taking your time to respond. Gotta love updates...

**Comment by NobleStrike** [comment]
Have you considered making artificial entities to trick the server to think it's a player with a view distance of like 1 as a loophole? Not even sure if that would be possible. Just throwing out ideas. Your plugin keeps landing spots for random events (asteroids and portal formations for arena fights) loaded in my server. Hence it's very important to me and I appreciate your plugin greatly.

**Comment by NobleStrike** [comment]
Was force loading removed from the plugin? Ive found that I can keep chunks loaded with /forceload so far without issue. Unless your aware of something that still breaks it soon after forcing chunks to be loaded

**Comment by NobleStrike** [comment]
/Forceload is busted for papermc, chunks get unloaded and the server still thinks its loaded. And when you run /forceload add it fails until you remove it first, even though the chunks arent loaded. Im going to report it to paper to see if it can be fixed.

**Comment by NobleStrike** [comment]
After further testing this behavior is NOT due to your plugin. Forceloading does it on its own.

Also not really sure where I could contact you about this, but I made a ticket with papermc to get forceloading working again. Which would mean it should let your plugin run if it using forceloading.

https://github.com/PaperMC/Paper/issues/2322

This ticket can be closed, Hopefully soon your plugin will work on paper at least.
