### ISSUE TITLE
keepregion only works if second coordinates are greater or equal than first

### ISSUE THREAD

**Issue by EmbersArc** [Geitenijs/KeepChunks#9]
**Describe the bug**
The command keepregion only works if second coordinates are greater or equal than first

**To Reproduce**
1. Execute command '/keepregion coords <x1> <z1> <x2> <z2> world' where x2 < x1 and/or z2
< z1.
2. Nothing happens, no error is shown.

**Expected behavior**
A region is kept no matter the relative size of the coordinates, or an error is shown.

**Environment (please complete the following information):**
 - Linux
 - Server Software: Paper
 - Server Version: 1.14.3
 - WorldEdit 7.0.0;214af8a

**Comment by Geitenijs** [comment]
I'm aware of this issue, however I don't have a fix ready. A PR would be very helpful :)

**Comment by EmbersArc** [comment]
https://github.com/Geitenijs/KeepChunks/pull/12

I've never written Java before and haven't tested it. So check before merging ;)

**Comment by Geitenijs** [comment]
Should be fixed in 1.5.13. Will be released later today.

**Comment by EmbersArc** [comment]
Works! Thank you.
